import type {StoredMedia} from "./evia-model";
const DB_NAME="evia-self-observation-media",DB_STORE="files";
export function readLocal<T>(key:string,fallback:T):T{if(typeof window==="undefined")return fallback;try{const value=window.localStorage.getItem(key);return value?(JSON.parse(value) as T):fallback}catch{return fallback}}
export function writeLocal(key:string,value:unknown){if(typeof window==="undefined")return;window.localStorage.setItem(key,JSON.stringify(value))}
function openMediaDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(DB_STORE))request.result.createObjectStore(DB_STORE,{keyPath:"id"})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
export async function storeMedia(blob:Blob,name:string,type:string){const db=await openMediaDb(),id=`m-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;await new Promise<void>((resolve,reject)=>{const transaction=db.transaction(DB_STORE,"readwrite");transaction.objectStore(DB_STORE).put({id,blob,name,type,createdAt:Date.now()} satisfies StoredMedia);transaction.oncomplete=()=>resolve();transaction.onerror=()=>reject(transaction.error)});db.close();return id}
export async function getMedia(id?:string):Promise<StoredMedia|null>{if(!id)return null;const db=await openMediaDb();const value=await new Promise<StoredMedia|null>((resolve,reject)=>{const request=db.transaction(DB_STORE,"readonly").objectStore(DB_STORE).get(id);request.onsuccess=()=>resolve((request.result as StoredMedia|undefined)??null);request.onerror=()=>reject(request.error)});db.close();return value}
function crc32(data:Uint8Array){let crc=0xffffffff;for(let i=0;i<data.length;i+=1){crc^=data[i];for(let j=0;j<8;j+=1)crc=(crc>>>1)^(0xedb88320&-(crc&1))}return(crc^0xffffffff)>>>0}
function concatBytes(parts:Uint8Array[]){const size=parts.reduce((total,part)=>total+part.length,0),out=new Uint8Array(size);let offset=0;parts.forEach(part=>{out.set(part,offset);offset+=part.length});return out}
function le16(value:number){return new Uint8Array([value&0xff,(value>>>8)&0xff])}
function le32(value:number){return new Uint8Array([value&0xff,(value>>>8)&0xff,(value>>>16)&0xff,(value>>>24)&0xff])}
function dosDateTime(date=new Date()){const year=Math.max(1980,date.getFullYear()),time=(date.getHours()<<11)|(date.getMinutes()<<5)|Math.floor(date.getSeconds()/2),day=((year-1980)<<9)|((date.getMonth()+1)<<5)|date.getDate();return{time,day}}
export function createStoredZip(files:{name:string;data:Uint8Array}[]){const encoder=new TextEncoder(),localParts:Uint8Array[]=[],centralParts:Uint8Array[]=[];let offset=0;const{time,day}=dosDateTime();files.forEach(file=>{const name=encoder.encode(file.name),crc=crc32(file.data),local=concatBytes([le32(0x04034b50),le16(20),le16(0),le16(0),le16(time),le16(day),le32(crc),le32(file.data.length),le32(file.data.length),le16(name.length),le16(0),name,file.data]);localParts.push(local);centralParts.push(concatBytes([le32(0x02014b50),le16(20),le16(20),le16(0),le16(0),le16(time),le16(day),le32(crc),le32(file.data.length),le32(file.data.length),le16(name.length),le16(0),le16(0),le16(0),le16(0),le32(0),le32(offset),name]));offset+=local.length});const local=concatBytes(localParts),central=concatBytes(centralParts),end=concatBytes([le32(0x06054b50),le16(0),le16(0),le16(files.length),le16(files.length),le32(central.length),le32(local.length),le16(0)]);return new Blob([local,central,end],{type:"application/zip"})}
