"use client";
import{type ChangeEvent,type FormEvent,useEffect,useMemo,useRef,useState}from"react";
import{COURSE_CODES,SITE_CATEGORIES,findOpportunityForCode,ksbType,type EvidenceOpportunity,type SiteCategory,type SiteJob}from"./evia-data";
import{createStoredZip,getMedia,readLocal,storeMedia,writeLocal}from"./evia-storage";
import{EviaShell}from"./evia-shell";
import{STORAGE,csvCell,formatDate,safeFileName,type AccessibilitySettings,type AnswerMode,type CourseTimeline,type DayRecap,type EpaArea,type EvidenceEntry,type EvidenceTab,type EviaExpression,type OtjEntry,type ProgressItem,type View}from"./evia-model";

export default function Home(){
const[ready,setReady]=useState(false),[open,setOpen]=useState(false),[view,setView]=useState<View>("root"),[expression,setExpression]=useState<EviaExpression>("idle"),[onboardingChecked,setOnboardingChecked]=useState(false),[onboardingStep,setOnboardingStep]=useState<number|null>(null),[fullName,setFullName]=useState(""),[timeline,setTimeline]=useState<CourseTimeline>({startDate:"",endDate:"",weeklyHours:37}),[entries,setEntries]=useState<EvidenceEntry[]>([]),[dayEntryIds,setDayEntryIds]=useState<string[]>([]),[lastRecap,setLastRecap]=useState<DayRecap|null>(null),[otjEntries,setOtjEntries]=useState<OtjEntry[]>([]),[epaCounts,setEpaCounts]=useState<Record<EpaArea,number>>({practical:0,interview:0,knowledge:0}),[accessibility,setAccessibility]=useState<AccessibilitySettings>({textSize:"standard",highContrast:false,reduceMotion:false});
const[selectedCategory,setSelectedCategory]=useState<SiteCategory|null>(null),[selectedJob,setSelectedJob]=useState<SiteJob|null>(null),[selectedOpportunity,setSelectedOpportunity]=useState<EvidenceOpportunity|null>(null),[photoFile,setPhotoFile]=useState<File|null>(null),[photoPreview,setPhotoPreview]=useState(""),[answerMode,setAnswerMode]=useState<AnswerMode>("type"),[typedAnswer,setTypedAnswer]=useState(""),[recordedAudio,setRecordedAudio]=useState<Blob|null>(null),[recording,setRecording]=useState(false),[recordSeconds,setRecordSeconds]=useState(0),[saving,setSaving]=useState(false),[evidenceTab,setEvidenceTab]=useState<EvidenceTab>("new"),[selectedEvidenceId,setSelectedEvidenceId]=useState(""),[selectedEvidencePhotoUrl,setSelectedEvidencePhotoUrl]=useState(""),[selectedEvidenceAudioUrl,setSelectedEvidenceAudioUrl]=useState(""),[ksbFilter,setKsbFilter]=useState<"All"|"Knowledge"|"Skill"|"Behaviour">("All"),[notice,setNotice]=useState(""),[remindersOpen,setRemindersOpen]=useState(false),[contextHelpOpen,setContextHelpOpen]=useState(false),[otjDraft,setOtjDraft]=useState({date:new Date().toISOString().slice(0,10),title:"",hours:"1"});
const noticeTimer=useRef<ReturnType<typeof setTimeout>|null>(null),mediaRecorderRef=useRef<MediaRecorder|null>(null),mediaStreamRef=useRef<MediaStream|null>(null),audioChunksRef=useRef<Blob[]>([]),recordTimerRef=useRef<ReturnType<typeof setInterval>|null>(null);
useEffect(()=>{const f=requestAnimationFrame(()=>setReady(true));return()=>cancelAnimationFrame(f)},[]);
useEffect(()=>{const name=window.localStorage.getItem(STORAGE.name)??"",done=window.localStorage.getItem(STORAGE.onboarding)==="true";setFullName(name);setTimeline(readLocal(STORAGE.timeline,{startDate:"",endDate:"",weeklyHours:37}));setEntries(readLocal<EvidenceEntry[]>(STORAGE.evidence,[]));setDayEntryIds(readLocal<string[]>(STORAGE.dayIds,[]));setLastRecap(readLocal<DayRecap|null>(STORAGE.recap,null));setOtjEntries(readLocal<OtjEntry[]>(STORAGE.otj,[]));setEpaCounts(readLocal(STORAGE.epa,{practical:0,interview:0,knowledge:0}));setAccessibility(readLocal(STORAGE.access,{textSize:"standard",highContrast:false,reduceMotion:false}));setOnboardingStep(done?null:0);setOnboardingChecked(true)},[]);
useEffect(()=>{if(!ready||accessibility.reduceMotion)return;const xs:EviaExpression[]=["idle","look-down","look-up-left","look-up-right","smile"],t=window.setInterval(()=>setExpression(xs[Math.floor(Math.random()*xs.length)]),5200);return()=>window.clearInterval(t)},[ready,accessibility.reduceMotion]);
const showNotice=(m:string)=>{setNotice(m);if(noticeTimer.current)clearTimeout(noticeTimer.current);noticeTimer.current=setTimeout(()=>setNotice(""),3000)},saveEntries=(x:EvidenceEntry[])=>{setEntries(x);writeLocal(STORAGE.evidence,x)},saveDayIds=(x:string[])=>{setDayEntryIds(x);writeLocal(STORAGE.dayIds,x)};
const ksbCounts=useMemo(()=>{const x:Record<string,number>={};COURSE_CODES.forEach(c=>x[c]=0);entries.forEach(e=>e.codes.forEach(c=>x[c]=(x[c]??0)+1));return x},[entries]),touchedKsbCount=useMemo(()=>COURSE_CODES.filter(c=>(ksbCounts[c]??0)>0).length,[ksbCounts]),newEntries=useMemo(()=>entries.filter(e=>!e.downloadedAt),[entries]),downloadedEntries=useMemo(()=>entries.filter(e=>!!e.downloadedAt),[entries]);
const selectedEvidence=entries.find(e=>e.id===selectedEvidenceId)??null,opportunityCount=(id:string)=>entries.filter(e=>e.opportunityId===id).length,jobCount=(id:string)=>entries.filter(e=>e.jobId===id).length,categoryCount=(id:string)=>entries.filter(e=>e.categoryId===id).length,currentDayEntries=entries.filter(e=>dayEntryIds.includes(e.id));
const tocProgress=useMemo(()=>{if(!timeline.startDate||!timeline.endDate)return 0;const s=new Date(`${timeline.startDate}T00:00:00`).getTime(),e=new Date(`${timeline.endDate}T23:59:59`).getTime();return!Number.isFinite(s)||!Number.isFinite(e)||e<=s?0:Math.round(Math.max(0,Math.min(1,(Date.now()-s)/(e-s)))*100)},[timeline]),ksbProgress=Math.round(touchedKsbCount/COURSE_CODES.length*100),otjHours=otjEntries.reduce((n,e)=>n+Number(e.hours||0),0),otjTarget=578,otjProgress=Math.round(Math.min(1,otjHours/otjTarget)*100),epaProgress=Math.round(Math.min(1,Object.values(epaCounts).reduce((a,b)=>a+b,0)/6)*100);
const progressItems:ProgressItem[]=[{label:"TOC",name:"Time on course",value:tocProgress,onClick:()=>{setOpen(true);setView("toc")}},{label:"KSB",name:"Evidence coverage",value:ksbProgress,onClick:()=>{setOpen(true);setView("ksb")}},{label:"OTJ",name:"Off the job",value:otjProgress,onClick:()=>{setOpen(true);setView("otj")}},{label:"EPA",name:"EPA practice",value:epaProgress,onClick:()=>{setOpen(true);setView("epa")}}];
const rootRecap=dayEntryIds.length?`You have collected ${currentDayEntries.length} evidence ${currentDayEntries.length===1?"moment":"moments"} today. Keep going or finish the day whenever you want.`:lastRecap?`Last time you collected ${lastRecap.evidenceCount} evidence ${lastRecap.evidenceCount===1?"moment":"moments"}. You now have evidence against ${touchedKsbCount} of ${COURSE_CODES.length} KSBs.`:"Pick the job that looks most like what you are doing. I’ll show you the evidence you could collect from it.";
function stopRecording(silent=false){if(recordTimerRef.current)clearInterval(recordTimerRef.current);recordTimerRef.current=null;const r=mediaRecorderRef.current;if(r&&r.state!=="inactive"){if(silent)r.onstop=null;try{r.stop()}catch{}}mediaStreamRef.current?.getTracks().forEach(t=>t.stop());mediaStreamRef.current=null;mediaRecorderRef.current=null;setRecording(false)}
const resetCapture=()=>{if(photoPreview)URL.revokeObjectURL(photoPreview);setPhotoFile(null);setPhotoPreview("");setTypedAnswer("");setRecordedAudio(null);setAnswerMode("type");setRecordSeconds(0);stopRecording(true)},navigate=(v:View)=>{setContextHelpOpen(false);setRemindersOpen(false);setView(v)},openCategory=(x:SiteCategory)=>{setSelectedCategory(x);setSelectedJob(null);navigate("jobs")},openJob=(x:SiteJob)=>{setSelectedJob(x);navigate("opportunities")},openOpportunity=(x:EvidenceOpportunity)=>{resetCapture();setSelectedOpportunity(x);navigate(x.media==="talk"?"question":"capture")};
const goBack=()=>{if(view==="jobs")navigate("root");else if(view==="opportunities")navigate("jobs");else if(view==="capture"||view==="question")navigate("opportunities");else if(view==="answer")navigate("question");else if(view==="evidence-detail")navigate("evidence");else navigate("root")};
const handlePhoto=(event:ChangeEvent<HTMLInputElement>)=>{const f=event.target.files?.[0]??null;event.target.value="";if(!f)return;if(photoPreview)URL.revokeObjectURL(photoPreview);setPhotoFile(f);setPhotoPreview(URL.createObjectURL(f))};
const startRecording=async()=>{if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==="undefined"){showNotice("Microphone recording is not supported here. Use Type instead.");return}try{stopRecording(true);const stream=await navigator.mediaDevices.getUserMedia({audio:true}),r=new MediaRecorder(stream);mediaStreamRef.current=stream;mediaRecorderRef.current=r;audioChunksRef.current=[];r.ondataavailable=e=>{if(e.data.size)audioChunksRef.current.push(e.data)};r.onstop=()=>{const b=new Blob(audioChunksRef.current,{type:r.mimeType||"audio/webm"});if(b.size)setRecordedAudio(b);mediaStreamRef.current?.getTracks().forEach(t=>t.stop());mediaStreamRef.current=null;mediaRecorderRef.current=null;setRecording(false)};r.start(250);setRecordedAudio(null);setRecordSeconds(0);setRecording(true);recordTimerRef.current=setInterval(()=>setRecordSeconds(s=>s+1),1000)}catch{showNotice("Microphone permission was not available. Use Type instead.")}};
const saveEvidenceMoment=async()=>{if(!selectedCategory||!selectedJob||!selectedOpportunity||saving)return;if(selectedOpportunity.media!=="talk"&&!photoFile){showNotice("Add one photo first.");return}if(answerMode==="type"&&typedAnswer.trim().split(/\s+/).filter(Boolean).length<3){showNotice("Just add a little more so I know what you mean.");return}if(answerMode==="talk"&&!recordedAudio){showNotice("Record a short answer first.");return}setSaving(true);try{let photoId:string|undefined,audioId:string|undefined;const now=Date.now();if(photoFile)photoId=await storeMedia(photoFile,photoFile.name||`${selectedOpportunity.id}.jpg`,photoFile.type||"image/jpeg");if(recordedAudio)audioId=await storeMedia(recordedAudio,`${selectedOpportunity.id}-${now}.webm`,recordedAudio.type||"audio/webm");const entry:EvidenceEntry={id:`e-${now}-${Math.random().toString(36).slice(2,7)}`,createdAt:now,categoryId:selectedCategory.id,categoryTitle:selectedCategory.title,jobId:selectedJob.id,jobTitle:selectedJob.title,opportunityId:selectedOpportunity.id,title:selectedOpportunity.title,bundle:selectedOpportunity.bundle,instruction:selectedOpportunity.instruction,question:selectedOpportunity.question,codes:[...selectedOpportunity.codes],answerMode,answerText:answerMode==="type"?typedAnswer.trim():undefined,photoId,photoName:photoFile?.name,audioId,audioName:audioId?`${safeFileName(selectedOpportunity.title)}-${now}.webm`:undefined};saveEntries([entry,...entries]);saveDayIds([...dayEntryIds,entry.id]);resetCapture();setExpression("smile");showNotice("Evidence saved. That took about a minute.");navigate("opportunities")}catch(e){console.error(e);showNotice("That evidence could not be saved on this device.")}finally{setSaving(false)}};
const submitJobAndHome=()=>{setSelectedJob(null);setSelectedOpportunity(null);setSelectedCategory(null);resetCapture();navigate("root");setOpen(false);showNotice("Job submitted. Start another job whenever you are ready.")},finishToday=()=>{const recap:DayRecap={finishedAt:Date.now(),evidenceCount:currentDayEntries.length,ksbTouched:touchedKsbCount};setLastRecap(recap);writeLocal(STORAGE.recap,recap);saveDayIds([]);setSelectedCategory(null);setSelectedJob(null);setSelectedOpportunity(null);resetCapture();navigate("root");setOpen(false);showNotice(currentDayEntries.length?`Day finished with ${currentDayEntries.length} evidence ${currentDayEntries.length===1?"moment":"moments"}.`:"Day finished. Nothing was forced or marked missing.")};
const openEvidenceDetail=async(entry:EvidenceEntry)=>{if(selectedEvidencePhotoUrl)URL.revokeObjectURL(selectedEvidencePhotoUrl);if(selectedEvidenceAudioUrl)URL.revokeObjectURL(selectedEvidenceAudioUrl);setSelectedEvidenceId(entry.id);setSelectedEvidencePhotoUrl("");setSelectedEvidenceAudioUrl("");navigate("evidence-detail");try{const[p,a]=await Promise.all([getMedia(entry.photoId),getMedia(entry.audioId)]);if(p?.blob)setSelectedEvidencePhotoUrl(URL.createObjectURL(p.blob));if(a?.blob)setSelectedEvidenceAudioUrl(URL.createObjectURL(a.blob))}catch{}};
const downloadNewEvidence=async()=>{if(!newEntries.length){showNotice("There is no new evidence waiting for Aptem.");return}setSaving(true);try{const files:{name:string;data:Uint8Array}[]=[],rows:any[][]=[["Evidence ID","Date","Job","Evidence","Question","Answer","KSBs"]],enc=new TextEncoder();for(let i=0;i<newEntries.length;i+=1){const e=newEntries[i],prefix=`${String(i+1).padStart(2,"0")}-${safeFileName(e.title)}`,answer=e.answerMode==="type"?e.answerText??"":"See audio recording";rows.push([e.id,formatDate(e.createdAt),e.jobTitle,e.title,e.question,answer,e.codes.join(" ")]);files.push({name:`${prefix}.txt`,data:enc.encode(["Evia Evidence",`Evidence ID: ${e.id}`,`Date: ${formatDate(e.createdAt)}`,`Job: ${e.jobTitle}`,`Evidence: ${e.title}`,`KSBs: ${e.codes.join(" · ")}`,"",`Evia asked: ${e.question}`,`Learner answer: ${answer}`].join("\r\n"))});const p=await getMedia(e.photoId);if(p){const ext=p.name.includes(".")?p.name.slice(p.name.lastIndexOf(".")):".jpg";files.push({name:`${prefix}-photo${ext}`,data:new Uint8Array(await p.blob.arrayBuffer())})}const a=await getMedia(e.audioId);if(a)files.push({name:`${prefix}-answer.webm`,data:new Uint8Array(await a.blob.arrayBuffer())})}files.unshift({name:"Evia-New-Evidence.csv",data:enc.encode(rows.map(r=>r.map(csvCell).join(",")).join("\r\n"))});const zip=createStoredZip(files),url=URL.createObjectURL(zip),a=document.createElement("a");a.href=url;a.download=`Evia-Aptem-New-Evidence-${new Date().toISOString().slice(0,10)}.zip`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);const when=Date.now();saveEntries(entries.map(e=>!e.downloadedAt?{...e,downloadedAt:when}:e));setEvidenceTab("downloaded");showNotice(`${newEntries.length} new evidence ${newEntries.length===1?"item":"items"} downloaded and moved to the archive.`)}catch(e){console.error(e);showNotice("The evidence download could not be built.")}finally{setSaving(false)}};
const routeFromKsb=(code:string)=>{const r=findOpportunityForCode(code);if(!r)return;setSelectedCategory(r.category);setSelectedJob(r.job);setSelectedOpportunity(r.opportunity);resetCapture();navigate(r.opportunity.media==="talk"?"question":"capture")};
const submitName=(event:FormEvent)=>{event.preventDefault();const n=fullName.trim();if(!n)return;window.localStorage.setItem(STORAGE.name,n);setFullName(n);setOnboardingStep(1)},completeOnboarding=()=>{window.localStorage.setItem(STORAGE.onboarding,"true");setOnboardingStep(null)},saveTimeline=(event:FormEvent)=>{event.preventDefault();writeLocal(STORAGE.timeline,timeline);showNotice("Course timeline saved.")},addOtj=(event:FormEvent)=>{event.preventDefault();const h=Number(otjDraft.hours);if(!otjDraft.title.trim()||!Number.isFinite(h)||h<=0)return;const x=[{id:`o-${Date.now()}`,date:otjDraft.date,title:otjDraft.title.trim(),hours:h},...otjEntries];setOtjEntries(x);writeLocal(STORAGE.otj,x);setOtjDraft({date:new Date().toISOString().slice(0,10),title:"",hours:"1"});showNotice("Off-the-job learning saved.")},addEpaPractice=(area:EpaArea)=>{const x={...epaCounts,[area]:epaCounts[area]+1};setEpaCounts(x);writeLocal(STORAGE.epa,x);showNotice("EPA practice session added.")},saveAccessibility=(x:AccessibilitySettings)=>{setAccessibility(x);writeLocal(STORAGE.access,x);showNotice("Accessibility settings saved.")},saveProfile=(event:FormEvent)=>{event.preventDefault();window.localStorage.setItem(STORAGE.name,fullName.trim());showNotice("Profile saved.")};
const viewTitle:Record<View,string>={root:"",jobs:selectedCategory?.title??"Jobs",opportunities:selectedJob?.title??"Evidence today",capture:selectedOpportunity?.title??"Photo",question:"Quick question",answer:answerMode==="talk"?"Talk about it":"Write about it",evidence:"Evidence","evidence-detail":"Evidence moment",ksb:"Course coverage",toc:"Time on course",otj:"Off the job",epa:"EPA practice",settings:"Settings",profile:"Learner profile",accessibility:"Accessibility"},evidenceForTab=evidenceTab==="new"?newEntries:downloadedEntries,filteredCodes=COURSE_CODES.filter(code=>ksbFilter==="All"||ksbType(code)===ksbFilter);
const helpText=view==="root"?"Pick the job you are actually doing. I’ll show you the evidence opportunities that genuinely fit that job.":view==="opportunities"?"These are opportunities, not a checklist. Capture the ones available today and leave the rest.":view==="capture"||view==="question"||view==="answer"?"Each evidence moment is one photo and one short explanation. It should normally take about a minute.":view==="ksb"?"Tap any KSB and I’ll take you directly to a suitable photo or question so you can strengthen it.":view==="evidence"?"New for Aptem only contains evidence gathered since your last download. Downloaded evidence stays in the archive and still counts.":"I’ll keep this page focused on one job at a time.";
const reminderItems=[...(lastRecap?[`Last day: ${lastRecap.evidenceCount} evidence moments · ${touchedKsbCount}/${COURSE_CODES.length} KSBs touched`]:[]),...(newEntries.length?[`${newEntries.length} new evidence ${newEntries.length===1?"item is":"items are"} ready for Aptem`]:[]),...(dayEntryIds.length?[`${currentDayEntries.length} evidence ${currentDayEntries.length===1?"moment":"moments"} collected today`]:[])],isOnboarding=onboardingChecked&&onboardingStep!==null;
const ctx={view,rootRecap,siteCategories:SITE_CATEGORIES,categoryCount,openCategory,newEntries,setEvidenceTab,navigate,downloadNewEvidence,saving,dayEntryIds,currentDayEntries,finishToday,selectedCategory,jobCount,openJob,selectedJob,openOpportunity,opportunityCount,submitJobAndHome,selectedOpportunity,photoPreview,handlePhoto,photoFile,setAnswerMode,typedAnswer,setTypedAnswer,saveEvidenceMoment,answerMode,recording,recordSeconds,recordedAudio,startRecording,stopRecording,evidenceTab,downloadedEntries,evidenceForTab,openEvidenceDetail,selectedEvidence,selectedEvidencePhotoUrl,selectedEvidenceAudioUrl,ksbFilter,setKsbFilter,filteredCodes,routeFromKsb,ksbCounts,tocProgress,timeline,setTimeline,saveTimeline,otjHours,otjTarget,otjDraft,setOtjDraft,addOtj,otjEntries,epaCounts,addEpaPractice,fullName,setFullName,saveProfile,accessibility,saveAccessibility};
return <EviaShell c={{ready,open,setOpen,view,expression,onboardingChecked,onboardingStep,fullName,setFullName,setOnboardingStep,accessibility,isOnboarding,setContextHelpOpen,contextHelpOpen,remindersOpen,setRemindersOpen,reminderItems,setView,viewTitle,goBack,ctx,progressItems,notice,helpText,submitName,completeOnboarding}}/>;
}
